Repository ResidenciaTICBrisa/05_PipelineFinatec, pull requests merged in 2023-08, with the labels that each got.

#17 Editando a home
  docs/assets/img/logo.png
  docs/atas/07-11.md
  docs/atas/07-20.md
  docs/atas/07-27.md
  docs/atas/08-01.md
  docs/index.md
  docs/treinamento/issues.md
  mkdocs.yml
Labels: documentação

#19 Atualização da home
  docs/index.md
Labels: documentação

#16 Documentação dos treinamentos no mkdocs
  .vscode/settings.json
  docs/treinamento/estudos_individuais/PipelinedeDados.md
  docs/treinamento/estudos_individuais/linguagem_framework.md
  docs/treinamento/estudos_individuais/metodologias.md
  docs/treinamento/introducao.md
  docs/treinamento/treinamentos/mkdocs.md
  docs/treinamento/treinamentos/pipelinesimples.md
  mkdocs.yml
Labels: documentação

#28 Corrigindo a pasta do deploy
  .github/workflows/deploy.yml
Labels: correção

#29 Atualizando a ata404
  docs/atas/07-11.md
  docs/atas/07-20.md
  docs/atas/07-27.md
  docs/atas/08-01.md
  mkdocs.yml
Labels: bug

#30 Atualizando Mkdocs
  docs/atas/07-11.md
  docs/atas/07-20.md
  docs/atas/07-27.md
  docs/atas/08-01.md
  mkdocs.yml
Labels: documentação, correção

#32 Adicionando ata
  docs/atas/08-10.md
  mkdocs.yml
Labels: documentação

#34 Organizando pastas e adicionando requisitos elicitados
  docs/planejamento/escopo.md
  docs/planejamento/fluxograma.md
  docs/planejamento/requisitos/elicitacao.md
  docs/planejamento/requisitos/priorizacao.md
  mkdocs.yml
Labels: documentação

#41 contexto, desafios e tecnologias utilizadas
  docs/planejamento/contexto.md
  docs/planejamento/teste.md
Labels: documentação

#42 Userstories
  docs/planejamento/backlog/backlog.md
  mkdocs.yml
Labels: documentação

#47 Story Mapping
  docs/planejamento/StoryMapping.md
  docs/planejamento/assets/incremental.png
  docs/planejamento/assets/mvp.png
  mkdocs.yml
Labels: documentação

#48 Adicionando Roadmap
  docs/planejamento/assets/roadmap.png
  docs/planejamento/roadmap.md
  mkdocs.yml
Labels: documentação

#51 Fluxograma
  docs/planejamento/assets/fluxograma.png
  docs/planejamento/fluxograma.md
Labels: documentação

#50 Adicionando o Roadmap
  docs/planejamento/assets/roadmap.png
  docs/planejamento/roadmap.md
  mkdocs.yml
Labels: documentação

#59 Estruturando dev
  project/app/__init__.py
  project/app/__pycache__/__init__.cpython-310.pyc
  project/app/__pycache__/admin.cpython-310.pyc
  project/app/__pycache__/apps.cpython-310.pyc
  project/app/__pycache__/models.cpython-310.pyc
  project/app/__pycache__/urls.cpython-310.pyc
  project/app/__pycache__/views.cpython-310.pyc
  project/app/admin.py
  project/app/apps.py
  project/app/migrations/__init__.py
  project/app/migrations/__pycache__/__init__.cpython-310.pyc
  project/app/models.py
  project/app/templates/base.html
  project/app/templates/home.html
  project/app/tests.py
  project/app/urls.py
  project/app/views.py
  project/db.sqlite3
  project/manage.py
  project/project/__init__.py
  project/project/__pycache__/__init__.cpython-310.pyc
  project/project/__pycache__/settings.cpython-310.pyc
  project/project/__pycache__/urls.cpython-310.pyc
  project/project/__pycache__/wsgi.cpython-310.pyc
  project/project/asgi.py
  project/project/settings.py
  project/project/urls.py
  project/project/wsgi.py
  src/codigo-inicial/FUNDEP-inicial.xlsx
  src/codigo-inicial/FUNDEP.xlsx
  src/codigo-inicial/app.py
  src/codigo-inicial/inicial.py
Labels: documentação

#77 Alteração do código inicial da fub
  project/app/__pycache__/__init__.cpython-311.pyc
  project/app/__pycache__/admin.cpython-311.pyc
  project/app/__pycache__/apps.cpython-311.pyc
  project/app/__pycache__/models.cpython-311.pyc
  project/app/__pycache__/urls.cpython-311.pyc
  project/app/__pycache__/views.cpython-311.pyc
  project/app/migrations/__pycache__/__init__.cpython-311.pyc
  project/db.sqlite3
  project/project/__pycache__/__init__.cpython-311.pyc
  project/project/__pycache__/settings.cpython-311.pyc
  project/project/__pycache__/urls.cpython-311.pyc
  project/project/__pycache__/wsgi.cpython-311.pyc
  src/codigo-inicial/antigo_dev.py
Labels: preencher planilha

#78 Mkdocs
  docs/planejamento/contexto.md
  mkdocs.yml
Labels: documentação

#79 Atualização mkdocs
  docs/index.md
  docs/planejamento/assets/logo.png
  docs/planejamento/backlog/backlog.md
  docs/planejamento/backlog/backlog1.md
  docs/planejamento/requisitos/priorizacao.md
  docs/planejamento/roadmap.md
  mkdocs.yml
Labels: documentação

#124 Atualizando documentação
  docs/index.md
  docs/planejamento/assets/logo.png
  docs/planejamento/backlog/backlog.md
  docs/planejamento/backlog/backlog1.md
  docs/planejamento/requisitos/priorizacao.md
  docs/planejamento/roadmap.md
  mkdocs.yml
Labels: documentação

#126 Adicionando conexão do postgre ao Django
  project/project/settings.py
Labels: backend
