Repository ResidenciaTICBrisa/05_PipelineFinatec, pull requests merged in 2023-10, with the labels that each got.

#134 Atualizando dev para a main
  docs/index.md
  docs/planejamento/escopo.md
  docs/planejamento/heatmap.md
  docs/planejamento/metodologia.md
  project/app/__init__.py
  project/app/__pycache__/__init__.cpython-310.pyc
  project/app/__pycache__/__init__.cpython-311.pyc
  project/app/__pycache__/admin.cpython-310.pyc
  project/app/__pycache__/admin.cpython-311.pyc
  project/app/__pycache__/apps.cpython-310.pyc
  project/app/__pycache__/apps.cpython-311.pyc
  project/app/__pycache__/models.cpython-310.pyc
  project/app/__pycache__/models.cpython-311.pyc
  project/app/__pycache__/urls.cpython-310.pyc
  project/app/__pycache__/urls.cpython-311.pyc
  project/app/__pycache__/views.cpython-310.pyc
  project/app/__pycache__/views.cpython-311.pyc
  project/app/admin.py
  project/app/apps.py
  project/app/migrations/__init__.py
  project/app/migrations/__pycache__/__init__.cpython-310.pyc
  project/app/migrations/__pycache__/__init__.cpython-311.pyc
  project/app/models.py
  project/app/static/css/style.css
  project/app/static/imagem/finateclogo.png
  project/app/static/imagem/logoFinatec.png
  project/app/templates/base.html
  project/app/templates/cadastro.html
  project/app/templates/cadastro_legado.html
  project/app/templates/login.html
  project/app/templates/login_legado.html
  project/app/templates/projeto.html
  project/app/templates/projeto_legado.html
  project/app/tests.py
  project/app/urls.py
  project/app/views.py
  project/db.sqlite3
  project/manage.py
  project/project/__init__.py
  project/project/__pycache__/__init__.cpython-310.pyc
  project/project/__pycache__/__init__.cpython-311.pyc
  project/project/__pycache__/settings.cpython-310.pyc
  project/project/__pycache__/settings.cpython-311.pyc
  project/project/__pycache__/urls.cpython-310.pyc
  project/project/__pycache__/urls.cpython-311.pyc
  project/project/__pycache__/wsgi.cpython-310.pyc
  project/project/__pycache__/wsgi.cpython-311.pyc
  project/project/asgi.py
  project/project/settings.py
  project/project/urls.py
  project/project/wsgi.py
  requirements.txt
  src/codigo-inicial/FUNDEP.xlsx
  src/codigo-inicial/antigo_dev.py
  src/codigo-inicial/app.py
  src/codigo-inicial/index.py
  src/codigo-inicial/inicial.py
  src/scripts/modeloTemplates.py
Labels: aperfeiçoamento

#135 Atualizando Mkdocs
  docs/index.md
  docs/treinamento/treinamentos/postgresql.md
  mkdocs.yml
Labels: documentação

#138 Implementação das models
  project/app/__pycache__/__init__.cpython-38.pyc
  project/app/__pycache__/admin.cpython-38.pyc
  project/app/__pycache__/apps.cpython-38.pyc
  project/app/__pycache__/models.cpython-38.pyc
  project/app/__pycache__/urls.cpython-38.pyc
  project/app/__pycache__/views.cpython-38.pyc
  project/app/migrations/0001_initial.py
  project/app/migrations/0002_rename_agencia_bancaria_mapeamento_agencia_bancaria_and_more.py
  project/app/migrations/__pycache__/0001_initial.cpython-38.pyc
  project/app/migrations/__pycache__/0002_rename_agencia_bancaria_mapeamento_agencia_bancaria_and_more.cpython-38.pyc
  project/app/migrations/__pycache__/__init__.cpython-38.pyc
  project/app/models.py
  project/project/__pycache__/__init__.cpython-38.pyc
  project/project/__pycache__/settings.cpython-38.pyc
  project/project/__pycache__/urls.cpython-38.pyc
  project/project/populando_banco.py
  project/project/settings.py
Labels: rastreamento, banco de dados

#140 Adicionando model de Lançamento
  project/app/migrations/0001_initial.py
  project/app/migrations/0002_rename_agencia_bancaria_mapeamento_agencia_bancaria_and_more.py
  project/app/models.py
Labels: aperfeiçoamento, banco de dados

#141 Adicionando o backend junto ao front
  project/app/models.py
  project/app/new_dev.py
  project/app/oracle_cruds.py
  project/app/planilhas/ModeloFAP.xlsx
  project/app/planilhas/ModeloFINEP.xlsx
  project/app/planilhas/ModeloFUNDEP.xlsx
  project/app/planilhas/ModeloOPAS.xlsx
  project/app/planilhas/Modelo_Fub.xlsx
  project/app/templates/projeto.html
  project/app/views.py
  project/project/settings.py
Labels: frontend, backend
